name: "Publish Sonar JSON to Pixee"
on:
  check_run:
    types: [completed]

jobs:
  publish:
    name: "Publish Sonar JSON to Pixee"
    runs-on: ubuntu-latest
    if: ${{ github.event.check_run.name == 'SonarCloud Code Analysis' }}
    steps:
      - uses: actions/checkout@v4

      - name: "Publish Sonar JSON to Pixee"
        shell: bash

        run: |
          echo $(curl -v "https://sonarcloud.io/api/issues/search?componentKeys=ryandens_auto-delegate&pullRequest=${{ github.event.check_run.pull_requests[0].number }}")
          echo "${{ github.event.check_run.pull_requests[0].head.sha }}"
